import type { OtherAssetItem } from './OtherAssetsTypes';

export const SAMPLE_OTHER_ASSETS: OtherAssetItem[] = [
  {
    id: 'asset-1',
    name: 'Prestige Golfshire Luxury Villa',
    category: 'Real Estate',
    subCategory: 'Residential Luxury Villa',
    propertyType: 'Residential',
    location: 'Nandi Hills Road, Bangalore, KA',
    acquisitionDate: '2021-04-15',
    costBasis: 24000000,
    currentValuation: 32000000,
    unrealizedGain: 8000000,
    unrealizedGainPercent: 33.33,
    rentalIncome: 85000,
    notes: '4 BHK luxury golf villa leased to corporate tenant on 3-year term.'
  },
  {
    id: 'asset-2',
    name: 'BKC Commercial Office Suite',
    category: 'Real Estate',
    subCategory: 'Grade-A Commercial Space',
    propertyType: 'Commercial',
    location: 'G-Block, Bandra Kurla Complex, Mumbai, MH',
    acquisitionDate: '2022-08-10',
    costBasis: 14500000,
    currentValuation: 18500000,
    unrealizedGain: 4000000,
    unrealizedGainPercent: 27.59,
    rentalIncome: 95000,
    notes: '1,200 sq.ft. fitted commercial office leased to financial advisory firm.'
  },
  {
    id: 'asset-3',
    name: 'Bitcoin Treasury Reserve',
    category: 'Crypto',
    subCategory: 'Layer-1 Digital Asset',
    cryptoSymbol: 'BTC',
    cryptoQuantity: 1.45,
    cryptoAvgPrice: 4482758,
    walletPlatform: 'Ledger Hardware Cold Storage',
    acquisitionDate: '2022-11-20',
    costBasis: 6500000,
    currentValuation: 10850000,
    unrealizedGain: 4350000,
    unrealizedGainPercent: 66.92,
    notes: 'Long-term sovereign store of value held in multi-sig air-gapped cold storage.'
  },
  {
    id: 'asset-4',
    name: 'Ethereum Strategic Holding',
    category: 'Crypto',
    subCategory: 'Layer-1 Smart Contracts',
    cryptoSymbol: 'ETH',
    cryptoQuantity: 12.50,
    cryptoAvgPrice: 192000,
    walletPlatform: 'Trezor Hardware Cold Storage',
    acquisitionDate: '2023-03-12',
    costBasis: 2400000,
    currentValuation: 3625000,
    unrealizedGain: 1225000,
    unrealizedGainPercent: 51.04,
    notes: 'Staked ETH generating decentralized validation yield.'
  },
  {
    id: 'asset-5',
    name: 'Sovereign Gold Bond 2023-24 Series III',
    category: 'Bonds',
    subCategory: 'Sovereign Gold Bond (SGB)',
    bondIssuer: 'Reserve Bank of India (RBI)',
    bondCouponRate: 2.50,
    bondPayoutFrequency: 'Semi-Annual',
    bondMaturityDate: '2031-12-28',
    acquisitionDate: '2023-12-28',
    costBasis: 1750000,
    currentValuation: 2280000,
    unrealizedGain: 530000,
    unrealizedGainPercent: 30.29,
    notes: 'Government backed. 2.5% semi-annual coupon + tax-free gold appreciation on maturity.'
  },
  {
    id: 'asset-6',
    name: 'NHAI Tax-Free Infrastructure Bonds',
    category: 'Bonds',
    subCategory: 'Tax-Free PSU Infrastructure Bond',
    bondIssuer: 'National Highways Authority of India',
    bondCouponRate: 7.60,
    bondPayoutFrequency: 'Annual',
    bondMaturityDate: '2028-01-15',
    acquisitionDate: '2020-01-15',
    costBasis: 1500000,
    currentValuation: 1520000,
    unrealizedGain: 20000,
    unrealizedGainPercent: 1.33,
    notes: 'Tax-exempt interest under Sec 10(15)(iv)(h) of Income Tax Act.'
  },
  {
    id: 'asset-7',
    name: '24K Minted Physical Gold Bullion',
    category: 'Gold & Metals',
    subCategory: 'Physical Gold Bars',
    metalWeightGrams: 250,
    metalPurity: '24K (99.99%)',
    custodian: 'HDFC Bank Safe Deposit Locker',
    acquisitionDate: '2022-10-24',
    costBasis: 1420000,
    currentValuation: 1850000,
    unrealizedGain: 430000,
    unrealizedGainPercent: 30.28,
    notes: 'Five 50-gram Swiss PAMP minted gold ingots with assay certificate.'
  },
  {
    id: 'asset-8',
    name: 'PayNova Fintech Series-A Angel Equity',
    category: 'Alternative',
    subCategory: 'Angel / Early Stage Venture',
    custodian: 'Private Share Registry (KFintech)',
    acquisitionDate: '2023-05-18',
    costBasis: 1000000,
    currentValuation: 2500000,
    unrealizedGain: 1500000,
    unrealizedGainPercent: 150.0,
    notes: '0.85% Series-A CCPS equity in fast growing B2B payments gateway.'
  }
];
